all: hello helloPI newline cha11x cha15x

hello: hello.cpp
	g++ -o hello hello.cpp
helloPI: helloPI.cpp
	g++ -o helloPI helloPI.cpp
newline: newline.cpp
	g++ -o newline newline.cpp
cha11x: cha11/main.cpp cha11/Time.cpp cha11/Time.h
	g++ -o cha11x cha11/main.cpp cha11/Time.cpp
cha15x: cha15/cha15.cpp cha15/matrix.cpp cha15/matrix.h
	g++ -o cha15x cha15/cha15.cpp
